import type { Metadata } from "next";
import "../styles/globals.css";
import vazirFont from "@/constants/localFont";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.variable} font-sans min-h-screen flex flex-col items-center`}>
        <Header/>
        <main className="container xl:max-w-screen-xl flex-1">
          {children}
        </main>
        <footer>فوتر سایت</footer>
      </body>
    </html>
  );
}
